version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: nest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nest-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: nest-redis
    restart: always
    ports:
      - "6379:6379"
